### ISSUE TITLE
我想学前端

### ISSUE THREAD

**Issue by KofClubs** [jindada1/jekyll#1]
好兄弟，带带我，呜呜呜

**Comment by jindada1** [comment]
来来来，一起折腾

> 好兄弟，带带我，呜呜呜

**Comment by KofClubs** [comment]
> 来来来，一起折腾
> 
> > 好兄弟，带带我，呜呜呜

等你作业搞得差不多了，教教我学前端，后端爷干不动了，盯终端眼睛都要瞎了。
